### PR TITLE
bump: Bump Mongoose version to 7.0.0

### PR DESCRIPTION
**Pull request by stenneepro**
#142 

- Upgrade mongoose version to 7.0.0 (callback is not supported for some functions from Mongoose 7.0.0)
- Remove bluebird
https://github.com/petkaantonov/bluebird#%EF%B8%8Fnote%EF%B8%8F

### CODE REVIEW

**Comment by stenneepro** [comment]
@viveleroi 
I closed the old PR and opened new one.

**Comment by viveleroi** [comment]
There was no reason to do that, but it's done so I'll review this and hopefully can get it merged today.

Replaces #143

**Comment by viveleroi** [comment]
Now this PR included reverts for my "fixes tests" commit. Are you brand new to git? 

I may need to take this over because we're not getting anywhere.

**Comment by stenneepro** [comment]
> Now this PR included reverts for my "fixes tests" commit. Are you brand new to git?
> 
> I may need to take this over because we're not getting anywhere.

OK, no problem.

**Comment by viveleroi** [comment]
Manually fixed this branch and merged in ce3e35a53f4400c2188519f4777ceb1af7ba05fe

**Pull request closed without merging**
