### PR TITLE
bump: Bump Mongoose version to 7.0.0

### PR DESCRIPTION
**Pull request by stenneepro**
#142 

- Upgrade mongoose version to 7.0.0 (callback is not supported for some functions from Mongoose 7.0.0)
- Remove bluebird
https://github.com/petkaantonov/bluebird#%EF%B8%8Fnote%EF%B8%8F

### CODE REVIEW

**Comment by ramazansancar** [comment]
@viveleroi check here :)

**Comment by viveleroi** [comment]
Please rebase this with master (I've pushed a fix to get tests running again) and look into why these three tests fail on this branch:

1. throws error for single nested index violation
2. throws error for index violation in an array of nested objects
3. does not throw error when create vs save data (with model field)

These all pass on master currently so either the tests need an update for promise-related changes or mongoose 7 is breaking them.

**Comment by stenneepro** [comment]
> Anything we can do in Mongoose to help get this merged? I'm also available to help debug any issues you have.

Yeah, I solved all problems.

**Comment by viveleroi** [comment]
All of these tests pass, thanks. There's something funky with the rebase, though because this PR now includes my last commit and your subsequent commit reverses the changes.

Please squash and then try a full rebase from master:

```
git fetch upstream
git pull --rebase upstream master
```

If I squashed and merged as-is this would revert the "fixes tests" commit.

**Comment by stenneepro** [comment]
> All of these tests pass, thanks. There's something funky with the rebase, though because this PR now includes my last commit and your subsequent commit reverses the changes.
> 
> Please squash and then try a full rebase from master:
> 
> ```
> git fetch upstream
> git pull --rebase upstream master
> ```
> 
> If I squashed and merged as-is this would revert the "fixes tests" commit.

Done

**Comment by viveleroi** [comment]
I don't understand how you're managing this branch. You now have 7 commits including duplicates of your own commits plus what I had pushed to master. This is a mess.

You'll need to fix history before this is mergeable. I suggest you cherry pick the correct commits onto a clean branch because at this point squashing would throw conflicts with your own branch.

**Pull request closed without merging**
